import { useCallback, useEffect, useMemo, useState } from "react";
import { fetchDistrictVendors } from "../api/district";

const currencyFormatter = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
});

function formatCurrency(value) {
  if (typeof value !== "number" || Number.isNaN(value)) {
    return "$0.00";
  }
  return currencyFormatter.format(value);
}

function formatHours(value) {
  if (typeof value !== "number" || Number.isNaN(value)) {
    return "0.00 hrs";
  }
  return `${value.toFixed(2)} hrs`;
}

function formatDate(value) {
  if (!value) {
    return "—";
  }
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return value;
  }
  return parsed.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export default function DistrictDashboard() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const response = await fetchDistrictVendors();
      setData(response);
      setError(null);
    } catch (err) {
      if (err?.response?.status === 403) {
        setError({ type: "forbidden", message: "District access is limited to admin accounts." });
      } else {
        console.error("Failed to load district dashboard", err);
        setError({ type: "error", message: "Unable to load vendor activity. Please try again." });
      }
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const totals = data?.totals ?? {};
  const vendorRows = data?.vendors ?? [];

  const summaryCards = useMemo(() => {
    if (!data) {
      return [];
    }
    return [
      { label: "Active Vendors", value: totals.vendors ?? 0 },
      { label: "Invoices Generated", value: totals.invoice_count ?? 0 },
      { label: "Total Hours", value: formatHours(totals.total_hours ?? 0) },
      { label: "Total Spend", value: formatCurrency(totals.total_cost ?? 0) },
    ];
  }, [data, totals]);

  return (
    <div className="space-y-8">
      <header className="flex items-start justify-between gap-4">
        <div>
          <h2 className="text-xl font-semibold">Active Vendors</h2>
          <p className="text-sm text-slate-600">
            Track invoice production across every partner after timesheets are uploaded on the vendor side.
          </p>
        </div>
        <button
          type="button"
          onClick={loadData}
          className="rounded-md border border-slate-300 px-3 py-1 text-sm font-medium text-slate-700 shadow-sm hover:bg-slate-100"
          disabled={loading}
        >
          {loading ? "Refreshing…" : "Refresh data"}
        </button>
      </header>

      {error ? (
        <div
          className={`rounded-md border px-4 py-3 text-sm ${
            error.type === "forbidden"
              ? "border-amber-200 bg-amber-50 text-amber-800"
              : "border-red-200 bg-red-50 text-red-700"
          }`}
        >
          {error.message}
        </div>
      ) : (
        <>
          <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {summaryCards.length ? (
              summaryCards.map((card) => (
                <div key={card.label} className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm">
                  <p className="text-xs uppercase tracking-wide text-slate-500">{card.label}</p>
                  <p className="mt-2 text-lg font-semibold text-slate-900">{card.value}</p>
                </div>
              ))
            ) : (
              <div className="sm:col-span-2 lg:col-span-4 rounded-lg border border-dashed border-slate-300 p-6 text-sm text-slate-500">
                No invoices have been processed yet. Once vendors upload timesheets the activity will populate here.
              </div>
            )}
          </section>

          <section className="space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold text-slate-900">Vendor invoice activity</h3>
              <p className="text-xs text-slate-500">
                Includes totals per vendor along with the latest student invoice generated by the automation.
              </p>
            </div>
            {vendorRows.length ? (
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-slate-200 text-left text-sm">
                  <thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500">
                    <tr>
                      <th className="px-3 py-2">Vendor</th>
                      <th className="px-3 py-2">Invoices</th>
                      <th className="px-3 py-2">Students</th>
                      <th className="px-3 py-2 text-right">Hours</th>
                      <th className="px-3 py-2 text-right">Total cost</th>
                      <th className="px-3 py-2">Most recent invoice</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {vendorRows.map((vendor) => (
                      <tr key={vendor.id} className="text-slate-700">
                        <td className="px-3 py-3">
                          <div className="font-medium text-slate-900">{vendor.name}</div>
                          <div className="text-xs text-slate-500">{vendor.contact_email}</div>
                        </td>
                        <td className="px-3 py-3">{vendor.invoice_count}</td>
                        <td className="px-3 py-3">{vendor.students_served}</td>
                        <td className="px-3 py-3 text-right">{formatHours(vendor.total_hours)}</td>
                        <td className="px-3 py-3 text-right">{formatCurrency(vendor.total_cost)}</td>
                        <td className="px-3 py-3">
                          {vendor.latest_invoice ? (
                            <div className="space-y-1">
                              <div className="text-sm font-medium text-slate-900">
                                {vendor.latest_invoice.invoice_number}
                              </div>
                              <div className="text-xs text-slate-500">
                                {vendor.latest_invoice.student_name} · {vendor.latest_invoice.service_month}
                              </div>
                              <div className="text-xs text-slate-500">
                                {formatDate(vendor.latest_invoice.invoice_date)} · {vendor.latest_invoice.status}
                              </div>
                              <div className="text-xs text-slate-500">
                                {formatCurrency(vendor.latest_invoice.total_cost)} · {formatHours(vendor.latest_invoice.total_hours)}
                              </div>
                              {vendor.latest_invoice.pdf_url && (
                                <a
                                  href={vendor.latest_invoice.pdf_url}
                                  target="_blank"
                                  rel="noopener noreferrer"
                                  className="inline-flex text-xs font-medium text-blue-600 hover:underline"
                                >
                                  View PDF
                                </a>
                              )}
                            </div>
                          ) : (
                            <span className="text-xs text-slate-500">No invoices on record.</span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <p className="text-sm text-slate-600">
                No vendor invoices have been recorded yet. Once vendors upload their timesheets you will see student-level
                activity here.
              </p>
            )}
          </section>
        </>
      )}
    </div>
  );
}
